### ISSUE TITLE
Dependency of UglifyJSSourcemapCompressor

### ISSUE THREAD

**Issue by andreashug** [moccu/barbeque#12]
`barbeque.compressor.UglifyJSSourcemapCompressor` imports `compressor.utils.stringformat` which has been removed from Compressor in version 2.0 (see https://github.com/django-compressor/django-compressor/commit/53d39114deb80a30543a994969d8a98bfa20476c )

**Comment by stephrdev** [comment]
Fixed in 1.0.1
