### ISSUE TITLE
exporter error

### ISSUE THREAD

**Issue by lenarother** [moccu/barbeque#17]
Hi!

When using action_export_factory for exporting xlsx one get:
```module 'openpyxl.cell' has no attribute 'get_column_letter'```

This is because of compatibility with the current version of openpyxl. barbeque requirements for exporter does not specify the version:
```
[exporter]
openpyxl
```

**Comment by stephrdev** [comment]
I'd like to se an pull request which 1) defines a version range for openpyxl and 2) updates the code to work with the current version of openpyxl.

**Comment by andreashug** [comment]
Please also mention the dependency on openpyxl in the documentaion:
https://barbeque.readthedocs.io/en/latest/exporter.html
